"""added table image

Revision ID: 8c33d72916cb
Revises: 42e541a231c8
Create Date: 2025-09-22 13:33:22.715731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c33d72916cb'
down_revision = '42e541a231c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.Column('public_id', sa.String(length=200), nullable=True),
    sa.Column('notes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notes_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
